// connectionActionTypes.js
export const SEND_CONNECTION_REQUEST = 'SEND_CONNECTION_REQUEST';
export const ACCEPT_CONNECTION_REQUEST = 'ACCEPT_CONNECTION_REQUEST';
export const GET_SENT_REQUESTS = 'GET_SENT_REQUESTS';
export const GET_RECEIVED_REQUESTS = 'GET_RECEIVED_REQUESTS';
export const GET_CONNECTIONS = 'GET_CONNECTIONS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
