export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const ORG_LOGIN_REQUEST="ORG_LOGIN_REQUEST";
export const ORG_LOGIN_SUCCESS="ORG_LOGIN_SUCCESS";
export const ORG_LOGIN_FAIL="ORG_LOGIN_FAIL";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const ORG_REGISTER_REQUEST="ORG_REGISTER_REQUEST";
export const ORG_REGISTER_SUCCESS="ORG_REGISTER_SUCCESS";
export const ORG_REGISTER_FAIL="ORG_REGISTER_FAIL";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";

export const LOGOUT_SUCCESS="LOGOUT_USER_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_USER_FAIL";


export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

// connectionActionTypes.js
export const SEND_CONNECTION_REQUEST = 'SEND_CONNECTION_REQUEST';
export const ACCEPT_CONNECTION_REQUEST = 'ACCEPT_CONNECTION_REQUEST';
export const GET_SENT_REQUESTS = 'GET_SENT_REQUESTS';
export const GET_RECEIVED_REQUESTS = 'GET_RECEIVED_REQUESTS';
export const GET_CONNECTIONS = 'GET_CONNECTIONS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';


export const CELAR_ERRORS="CLEAR_ERRORS";

